blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: https://github.com/naja-js/naja/discussions/new?category=support
    about: I am stuck and need help with Naja. ğŸ‘‰ Please ask for help in Discussions.
